### ISSUE TITLE
Support BOT API 7.1 (february 16 2024)

### ISSUE THREAD

**Issue by bernard-ng** [TelegramBot/Api#466]
documentation : https://core.telegram.org/bots/api#february-16-2024

## Tasks
- [x] Added support for the administrator rights can_post_stories, can_edit_stories, can_delete_stories in supergroups.
- [x] Added the class [ChatBoostAdded](https://core.telegram.org/bots/api#chatboostadded) and the field boost_added to the class [Message](https://core.telegram.org/bots/api#message) for service messages about a user boosting a chat.
- [x] Added the field sender_boost_count to the class [Message](https://core.telegram.org/bots/api#message).
- [x] Added the field reply_to_story to the class [Message](https://core.telegram.org/bots/api#message).
- [x] Added the fields chat and id to the class [Story](https://core.telegram.org/bots/api#story).
- [ ] Added the field unrestrict_boost_count to the class [Chat](https://core.telegram.org/bots/api#chat).
- [x] Added the field custom_emoji_sticker_set_name to the class [Chat](https://core.telegram.org/bots/api#chat).

**Comment by bernard-ng** [comment]
after verification, version 7.1 is fully supported
